<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PaymentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            ['value' => 130.00, 'rehabitation_center' => 1, 'service' => 1, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 140.22, 'rehabitation_center' => 1, 'service' => 2, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 159.90, 'rehabitation_center' => 1, 'service' => 3, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 140.22, 'rehabitation_center' => 1, 'service' => 4, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 159.90, 'rehabitation_center' => 1, 'service' => 5, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 130.00, 'rehabitation_center' => 1, 'service' => 6, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 140.22, 'rehabitation_center' => 1, 'service' => 7, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 159.90, 'rehabitation_center' => 1, 'service' => 8, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 140.22, 'rehabitation_center' => 1, 'service' => 9, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 140.22, 'rehabitation_center' => 1, 'service' => 10, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 159.90, 'rehabitation_center' => 1, 'service' => 11, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 140.22, 'rehabitation_center' => 1, 'service' => 12, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 51.66, 'rehabitation_center' => 1, 'service' => 13, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 31.25, 'rehabitation_center' => 1, 'service' => 15, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 6.25, 'rehabitation_center' => 1, 'service' => 16, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 140.22, 'rehabitation_center' => 1, 'service' => 18, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 159.90, 'rehabitation_center' => 1, 'service' => 22, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 51.66, 'rehabitation_center' => 1, 'service' => 23, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 195.00, 'rehabitation_center' => 1, 'service' => 30, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 100.00, 'rehabitation_center' => 1, 'service' => 31, 'status' => 1, 'is_flatrate_service' => 0],

            ['value' => 30.00, 'rehabitation_center' => 2, 'service' => 1, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 73.80, 'rehabitation_center' => 2, 'service' => 2, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 30.00, 'rehabitation_center' => 2, 'service' => 3, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 73.80, 'rehabitation_center' => 2, 'service' => 4, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 30.00, 'rehabitation_center' => 2, 'service' => 5, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 30.00, 'rehabitation_center' => 2, 'service' => 6, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 73.80, 'rehabitation_center' => 2, 'service' => 7, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 30.00, 'rehabitation_center' => 2, 'service' => 8, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 73.80, 'rehabitation_center' => 2, 'service' => 9, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 73.80, 'rehabitation_center' => 2, 'service' => 10, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 30.00, 'rehabitation_center' => 2, 'service' => 11, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 73.80, 'rehabitation_center' => 2, 'service' => 12, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 40.00, 'rehabitation_center' => 2, 'service' => 13, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 38.00, 'rehabitation_center' => 2, 'service' => 15, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 29.00, 'rehabitation_center' => 2, 'service' => 16, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 67.65, 'rehabitation_center' => 2, 'service' => 18, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 20.00, 'rehabitation_center' => 2, 'service' => 22, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 10.00, 'rehabitation_center' => 2, 'service' => 23, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 20.00, 'rehabitation_center' => 2, 'service' => 30, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 10.00, 'rehabitation_center' => 2, 'service' => 31, 'status' => 1, 'is_flatrate_service' => 0],

            ['value' => 70.00, 'rehabitation_center' => 3, 'service' => 1, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 3, 'service' => 2, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 3, 'service' => 3, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 3, 'service' => 4, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 3, 'service' => 5, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 70.00, 'rehabitation_center' => 3, 'service' => 6, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 3, 'service' => 7, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 3, 'service' => 8, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 3, 'service' => 9, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 3, 'service' => 10, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 3, 'service' => 11, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 3, 'service' => 12, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 90.00, 'rehabitation_center' => 3, 'service' => 13, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 90.00, 'rehabitation_center' => 3, 'service' => 15, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 85.00, 'rehabitation_center' => 3, 'service' => 16, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 100.00, 'rehabitation_center' => 3, 'service' => 18, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 3, 'service' => 22, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 100.00, 'rehabitation_center' => 3, 'service' => 23, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 70.00, 'rehabitation_center' => 3, 'service' => 30, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 30.00, 'rehabitation_center' => 3, 'service' => 31, 'status' => 1, 'is_flatrate_service' => 0],

            ['value' => 80.00, 'rehabitation_center' => 4, 'service' => 1, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 4, 'service' => 2, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 4, 'service' => 3, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 4, 'service' => 4, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 4, 'service' => 5, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 80.00, 'rehabitation_center' => 4, 'service' => 6, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 4, 'service' => 7, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 4, 'service' => 8, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 4, 'service' => 9, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 4, 'service' => 10, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 4, 'service' => 11, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 4, 'service' => 12, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 90.00, 'rehabitation_center' => 4, 'service' => 13, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 90.00, 'rehabitation_center' => 4, 'service' => 15, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 80.00, 'rehabitation_center' => 4, 'service' => 16, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 100.00, 'rehabitation_center' => 4, 'service' => 18, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 110.00, 'rehabitation_center' => 4, 'service' => 22, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 90.00, 'rehabitation_center' => 4, 'service' => 23, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 80.00, 'rehabitation_center' => 4, 'service' => 30, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 45.00, 'rehabitation_center' => 4, 'service' => 31, 'status' => 1, 'is_flatrate_service' => 0],

            ['value' => 51.66, 'rehabitation_center' => 1, 'service' => 14, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 6.25, 'rehabitation_center' => 1, 'service' => 17, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 140.22, 'rehabitation_center' => 1, 'service' => 19, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 123.00, 'rehabitation_center' => 1, 'service' => 20, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 1845.00, 'rehabitation_center' => 1, 'service' => 21, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 159.90, 'rehabitation_center' => 1, 'service' => 24, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 12838.74, 'rehabitation_center' => 1, 'service' => 25, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 123.00, 'rehabitation_center' => 1, 'service' => 26, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 80000.00, 'rehabitation_center' => 1, 'service' => 27, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 26000.00, 'rehabitation_center' => 1, 'service' => 28, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 28000.00, 'rehabitation_center' => 1, 'service' => 29, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 200.00, 'rehabitation_center' => 1, 'service' => 32, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 135.00, 'rehabitation_center' => 1, 'service' => 33, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 130.00, 'rehabitation_center' => 1, 'service' => 34, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 43.20, 'rehabitation_center' => 1, 'service' => 35, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 43.20, 'rehabitation_center' => 1, 'service' => 36, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 52.92, 'rehabitation_center' => 1, 'service' => 37, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 105.84, 'rehabitation_center' => 1, 'service' => 38, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 147.60, 'rehabitation_center' => 1, 'service' => 39, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 60.27, 'rehabitation_center' => 1, 'service' => 40, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 60024.00, 'rehabitation_center' => 1, 'service' => 41, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 48019.20, 'rehabitation_center' => 1, 'service' => 42, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 60024.00, 'rehabitation_center' => 1, 'service' => 43, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 90, 'rehabitation_center' => 1, 'service' => 44, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 10, 'rehabitation_center' => 1, 'service' => 45, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 124, 'rehabitation_center' => 1, 'service' => 46, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 1300, 'rehabitation_center' => 1, 'service' => 47, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 0, 'rehabitation_center' => 1, 'service' => 48, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 0, 'rehabitation_center' => 1, 'service' => 49, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 0, 'rehabitation_center' => 1, 'service' => 50, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 0, 'rehabitation_center' => 1, 'service' => 51, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 0, 'rehabitation_center' => 1, 'service' => 52, 'status' => 1, 'is_flatrate_service' => 1],

            ['value' => 40.00, 'rehabitation_center' => 2, 'service' => 14, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 29.00, 'rehabitation_center' => 2, 'service' => 17, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 67.65, 'rehabitation_center' => 2, 'service' => 19, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 307.50, 'rehabitation_center' => 2, 'service' => 20, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 2460.00, 'rehabitation_center' => 2, 'service' => 21, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 20.00, 'rehabitation_center' => 2, 'service' => 24, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 1500.00, 'rehabitation_center' => 2, 'service' => 25, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 120.00, 'rehabitation_center' => 2, 'service' => 26, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 215000.00, 'rehabitation_center' => 2, 'service' => 27, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 72000.00, 'rehabitation_center' => 2, 'service' => 28, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 71000.00, 'rehabitation_center' => 2, 'service' => 29, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 20.00, 'rehabitation_center' => 2, 'service' => 32, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 20.00, 'rehabitation_center' => 2, 'service' => 33, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 20.00, 'rehabitation_center' => 2, 'service' => 34, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 100.00, 'rehabitation_center' => 2, 'service' => 35, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 75.00, 'rehabitation_center' => 2, 'service' => 36, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 10.00, 'rehabitation_center' => 2, 'service' => 37, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 100.00, 'rehabitation_center' => 2, 'service' => 38, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 30.00, 'rehabitation_center' => 2, 'service' => 39, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 30.00, 'rehabitation_center' => 2, 'service' => 40, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 69300.00, 'rehabitation_center' => 2, 'service' => 41, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 55440.00, 'rehabitation_center' => 2, 'service' => 42, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 69300.00, 'rehabitation_center' => 2, 'service' => 43, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 106, 'rehabitation_center' => 2, 'service' => 44, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 10, 'rehabitation_center' => 2, 'service' => 45, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 112, 'rehabitation_center' => 2, 'service' => 46, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 2000, 'rehabitation_center' => 2, 'service' => 47, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 0, 'rehabitation_center' => 2, 'service' => 48, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 0, 'rehabitation_center' => 2, 'service' => 49, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 0, 'rehabitation_center' => 2, 'service' => 50, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 0, 'rehabitation_center' => 2, 'service' => 51, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 0, 'rehabitation_center' => 2, 'service' => 52, 'status' => 1, 'is_flatrate_service' => 1],

            ['value' => 90.00, 'rehabitation_center' => 3, 'service' => 14, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 90.00, 'rehabitation_center' => 3, 'service' => 17, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 100.00, 'rehabitation_center' => 3, 'service' => 19, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 150.00, 'rehabitation_center' => 3, 'service' => 20, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 12000.00, 'rehabitation_center' => 3, 'service' => 21, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 100.00, 'rehabitation_center' => 3, 'service' => 24, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 100.00, 'rehabitation_center' => 3, 'service' => 25, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 100.00, 'rehabitation_center' => 3, 'service' => 26, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 4000.00, 'rehabitation_center' => 3, 'service' => 27, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 1300.00, 'rehabitation_center' => 3, 'service' => 28, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 1400.00, 'rehabitation_center' => 3, 'service' => 29, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 80.00, 'rehabitation_center' => 3, 'service' => 32, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 80.00, 'rehabitation_center' => 3, 'service' => 33, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 60.00, 'rehabitation_center' => 3, 'service' => 34, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 85.00, 'rehabitation_center' => 3, 'service' => 35, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 60.00, 'rehabitation_center' => 3, 'service' => 36, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 40.00, 'rehabitation_center' => 3, 'service' => 37, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 140.00, 'rehabitation_center' => 3, 'service' => 38, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 60.00, 'rehabitation_center' => 3, 'service' => 39, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 60.00, 'rehabitation_center' => 3, 'service' => 40, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 55350.00, 'rehabitation_center' => 3, 'service' => 41, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 45800.00, 'rehabitation_center' => 3, 'service' => 42, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 55350.00, 'rehabitation_center' => 3, 'service' => 43, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 90, 'rehabitation_center' => 3, 'service' => 44, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 10, 'rehabitation_center' => 3, 'service' => 45, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 124, 'rehabitation_center' => 3, 'service' => 46, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 1300, 'rehabitation_center' => 3, 'service' => 47, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 0, 'rehabitation_center' => 3, 'service' => 48, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 0, 'rehabitation_center' => 3, 'service' => 49, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 0, 'rehabitation_center' => 3, 'service' => 50, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 0, 'rehabitation_center' => 3, 'service' => 51, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 0, 'rehabitation_center' => 3, 'service' => 52, 'status' => 1, 'is_flatrate_service' => 1],

            ['value' => 90.00, 'rehabitation_center' => 4, 'service' => 14, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 85.00, 'rehabitation_center' => 4, 'service' => 17, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 100.00, 'rehabitation_center' => 4, 'service' => 19, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 200.00, 'rehabitation_center' => 4, 'service' => 20, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 12000.00, 'rehabitation_center' => 4, 'service' => 21, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 100.00, 'rehabitation_center' => 4, 'service' => 24, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 100.00, 'rehabitation_center' => 4, 'service' => 25, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 100.00, 'rehabitation_center' => 4, 'service' => 26, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 12000.00, 'rehabitation_center' => 4, 'service' => 27, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 4000.00, 'rehabitation_center' => 4, 'service' => 28, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 0.00, 'rehabitation_center' => 4, 'service' => 29, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 150.00, 'rehabitation_center' => 4, 'service' => 32, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 150.00, 'rehabitation_center' => 4, 'service' => 33, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 150.00, 'rehabitation_center' => 4, 'service' => 34, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 90.00, 'rehabitation_center' => 4, 'service' => 35, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 40.00, 'rehabitation_center' => 4, 'service' => 36, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 35.00, 'rehabitation_center' => 4, 'service' => 37, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 130.00, 'rehabitation_center' => 4, 'service' => 38, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 130.00, 'rehabitation_center' => 4, 'service' => 39, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 130.00, 'rehabitation_center' => 4, 'service' => 40, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 55350.00, 'rehabitation_center' => 4, 'service' => 41, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 44280.00, 'rehabitation_center' => 4, 'service' => 42, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 55350.00, 'rehabitation_center' => 4, 'service' => 43, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 90, 'rehabitation_center' => 4, 'service' => 44, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 10, 'rehabitation_center' => 4, 'service' => 45, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 124, 'rehabitation_center' => 4, 'service' => 46, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 1300, 'rehabitation_center' => 4, 'service' => 47, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 0, 'rehabitation_center' => 4, 'service' => 48, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 0, 'rehabitation_center' => 4, 'service' => 49, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 0, 'rehabitation_center' => 4, 'service' => 50, 'status' => 1, 'is_flatrate_service' => 0],
            ['value' => 0, 'rehabitation_center' => 4, 'service' => 51, 'status' => 1, 'is_flatrate_service' => 1],
            ['value' => 0, 'rehabitation_center' => 4, 'service' => 52, 'status' => 1, 'is_flatrate_service' => 1],

        ];
        foreach($items as $item)
        {
            \App\Models\Payment::create($item);
        }
    }
}
